[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]       # isort
exclude = ["app/static", "app/templates"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
